apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: ahmadjamal710/todo-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_DNS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BACKEND_DNS
            - name: BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BACKEND_PORT
          resources:
            requests: {}
            limits: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: backend
          image: ahmadjamal710/todo-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DEBUG
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
          startupProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /health/
              port: 8000
          resources:
            requests: {}
            limits: {}
