grafana:
  adminUser: admin
  adminPassword: admin
  ingress:
    enabled: true
    path: /
    hosts:
      - grafana.todo-app.com
    annotations:
      kubernetes.io/ingress.class: nginx
prometheus:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - prometheus.todo-app.com
